### ISSUE TITLE
Error using online Peggy - Can't find variable: util

### ISSUE THREAD

**Issue by dselman** [peggyjs/peggy#371] opened 2023-03-06 13:43 UTC
When I use a parser within the [Peggy online editor](https://peggyjs.org/online.html) the parser displays an error:

```
Can't find variable: util
```

The same parser works when used from the command line or in a Node.js application.

The web-browser (latest Safari) displays the following two error messages in the console:

```
SyntaxError: Invalid regular expression: invalid group specifier name
TypeError: undefined is not an object (evaluating 'ann.from.line')
```

<img width="464" alt="image" src="https://user-images.githubusercontent.com/623108/223125734-ffb4429e-7bdc-4b4b-8c26-d4293a69abd4.png">

## To reproduce

1. Copy the peg grammar: https://github.com/accordproject/concerto/blob/main/packages/concerto-cto/lib/parser.pegjs
2. Paste the grammar into the editor and then type the following input text (which is valid and should create an AST):

```
namespace test
```

3. The error `Can't find variable: util` appears below the parser input window.

**Comment by Mingun** [comment] 2023-03-06 15:02
Doesn't reproduced for me. What exactly online editor did you mean? https://peggyjs.org/online? I tried to paste https://raw.githubusercontent.com/accordproject/concerto/main/packages/concerto-cto/lib/parser.pegjs an the parser was generated without errors. Input `namespace test` parsed as:
```js
{
  '$class': 'concerto.metamodel@1.0.0.Model',
  decorators: [],
  namespace: 'test',
  imports: [],
  declarations: []
}
```

**Comment by dselman** [comment] 2023-03-06 16:17
> Doesn't reproduced for me. 

Interesting! I just tried it in Chrome and it works, so it appears to be an issue specific to Safari. I am using `Version 16.2 (18614.3.7.1.5)`.

**Comment by hildjj** [comment] 2023-03-06 18:38
I can reproduce this in Safari.  This looks to be an error in [node-inspect-extracted](https://github.com/hildjj/node-inspect-extracted/).  I'm going to try updating to the latest version of that package first, then see if there is still a problem.

**Comment by hildjj** [comment] 2023-03-06 19:08
This should be fixed in Safari 16.4 according to [this](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/).  I think maybe we should just test for util being available, and fall back on `console.log("%O", result)` for those that have broken browsers.

**Comment by hildjj** [comment] 2023-03-06 19:20
OK, take a look at the pretty awful hack that is #372.  I'd rather not change the offending line in node-inspect-extracted for two reasons: capturing the intent of the negative lookbehind adequately will be a little tough, and b) I'm trying to keep that code as close to nodejs source as possible.

**Comment by Mingun** [comment] 2023-03-09 04:12
I forgot to mention, that I've checked on Firefox 110.0.1, but I also use the old Firefox ESR 52.9.0 because of its plugins, and this error affects it also (of course)

**Closed** 2023-03-17 15:36 UTC
