### ISSUE TITLE
switch order express order around "/" causes matching to fail

### ISSUE THREAD

**Issue by Louis-Tian** [peggyjs/peggy#358] opened 2023-02-27 04:59 UTC
```pegjs
value = list / word
list = head:(item:word "," { return item })+ tail:word { return [...head, tail] }
word = $[a-z0-9_]i+
```
works as expected. 
```
a,b => ['a','b']
a   => 'a'
```
Now, if I swap the order in the starting rule. list matching will fail
```pegjs
value = word / list  // swap order
list = head:(item:word "," { return item })+ tail:word { return [...head, tail] }
word = $[a-z0-9_]i+
```
now it won't match with list input. 
```
a,b => failed
a   => 'a' 
```
Seems like a bug?

**Comment by Mingun** [comment] 2023-02-27 05:18
This is expected behavior. Choice in [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) is ordered.

**Comment by Mingun** [comment] 2023-02-27 05:21
A side note: since 3.0 the canonical way to parse list is (equivalent to your grammar):
```pegjs
list = word|2.., ","|;
```

**Comment by Louis-Tian** [comment] 2023-02-27 05:41
> This is expected behavior. Choice in [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) is ordered.
Appreciate your reply.
I understand that "/" is ordered. If the first expression failed to match, it will try to match the second expression instead.

But I can't see how this would explain the behavior here. In the second case, we have the start rule as `word / list`, when the input is a list, it should still fall back to the second 'list' expression after failing to match the 'word' expression, isn't it?

**Comment by Mingun** [comment] 2023-02-27 07:40
Yes, but the problem in that that `word` rule is not failed. Moreover, the `list` rule is failed on all inputs where `word` failed (because it started with `word`), so in `word / list` the `list` alternative is useless -- it will always fail.

**Comment by Louis-Tian** [comment] 2023-02-27 09:08
> Yes, but the problem in that that `word` rule is not failed. 

mmm. I must be missing something here. 
Given the input string `a,b`, it won't match the word expression `[a-z0-9_]i+`, so the word rule should fail. No?

**Comment by Mingun** [comment] 2023-02-27 10:10
No. It matches `a` in the `word` rule and then marked `value` as matched on `a` (because alternative `word` is matched). Then it see that `value` is the start rule and tries to match EOF, which is failed because there are left unconsumed input `,b`. Because of this the whole grammar is failed to parse `a,b`.

**Comment by Louis-Tian** [comment] 2023-02-27 10:22
The [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) contains a section specifically for this behavior it seems. So not a bug indeed. Although, I still don't quite understand the reason behind it. 

> The ordering of productions in a PEG grammar affects not only the resolution of ambiguity, but also the language matched. For example, consider the first PEG example in Ford's paper[[1]](https://en.wikipedia.org/wiki/Parsing_expression_grammar#cite_note-For04-1) (example rewritten in pegjs.org/online notation, and labelled G_{1} and G_{2}):
> G_{1}:  A = "a" "b" / "a"
> G_{2}:  A = "a" / "a" "b"
> Ford notes that The second alternative in the latter PEG rule will never succeed because the first choice is always taken if the input string ... begins with 'a'.

The [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar)

**Comment by Mingun** [comment] 2023-02-27 10:29
Correct. The reason is unambiguity and linear parsing time (if use caching).

**Comment by hildjj** [comment] 2023-02-27 18:54
In these sorts of situations, turning on tracing helped to develop my intuition more rapidly.  Like this:

```sh
$ cat <<'EOF' | peggy --trace -t "a,b"
value = list / word
list = head:(item:word "," { return item })+ tail:word { return [...head, tail] }
word = $[a-z0-9_]i+
EOF
```

**Comment by hildjj** [comment] 2023-03-01 15:19
Closing because I think we've come to a conclusion.  Please reopen if you need more help.

**Closed by hildjj** 2023-03-01 15:19 UTC
