### ISSUE TITLE
Bug in negation predicate

### ISSUE THREAD

**Issue by mingodad** [peggyjs/peggy#277] opened 2022-06-06 08:32 UTC
While trying this grammar:
```
STRING_LONG =
	 '[' '='* '['  ( ! (']' '='* ']') . )* ']' '='* ']'
```
With this input:
```
[==[One string]]==]
```
I'm getting this error, while I was expecting none:
```
Line 1, column 17: Expected end of input but "=" found.
```
See discussion here: https://github.com/ChrisHixon/chpeg/issues/17#issuecomment-1146876233

**Comment by hildjj** [comment] 2022-06-06 09:17
After rewriting this as:

```peg.js
STRING_LONG =
	 start  nendd* end

nendd = nend c:. {console.log(c)}
nend = !end
start = '[' '='* '['
end = ']' '='* ']' {console.log('end', text())}
```

and running with tracing on: `bin/peggy.js t.peggy -t '[==[O]]==]' --trace`, this looks like it's working as designed to me.  I get this output:

```
1:1-1:1 rule.enter STRING_LONG
1:1-1:1 rule.enter   start
1:1-1:5 rule.match   start
1:5-1:5 rule.enter   nendd
1:5-1:5 rule.enter     nend
1:5-1:5 rule.enter       end
1:5-1:5 rule.fail        end
1:5-1:5 rule.match     nend
O
1:5-1:6 rule.match   nendd
1:6-1:6 rule.enter   nendd
1:6-1:6 rule.enter     nend
1:6-1:6 rule.enter       end
end ]]
1:6-1:8 rule.match       end
1:6-1:6 rule.fail      nend
1:6-1:6 rule.fail    nendd
1:6-1:6 rule.enter   end
end ]]
1:6-1:8 rule.match   end
1:1-1:8 rule.match STRING_LONG
Error running test
Error: Expected end of input but "=" found.
 --> command line:1:8
  |
1 | [==[O]]==]
  |        ^
```

The key being `end ]]`.  the `end` rule matches the `]]`.  Did you mean for there to be a + instead of a * in there?

**Comment by hildjj** [comment] 2022-06-06 09:29
Looking at the thread you point to, then reading about Lua strings, I think what you want is for the number of `=` in `start` to equal the number in `end`.

Here's a start at a working grammar:

```peg.js
{
const stack = []
}
STRING_LONG =
	 start c:$nendd* end { stack.pop(); return c; }

nendd = nend .
nend = !end
start = '[' e:'='* '[' { stack.push(e.length) }
end = ']' (e:'='* &{ return e.length === stack[stack.length - 1] }) ']'
```

It still needs some extra work to add nesting, but I think you can see the idea.

**Comment by Mingun** [comment] 2022-06-06 09:34
Because this is a Lua long string I suppose that @mingodad wants to store count of `=`:
```pegjs
{
var levels = [];
}
STRING_LONG = start content:content end { levels.pop(); return content; }

content = $(!end .)*;
start = '[' level:'='* '[' { levels.push(level.length); }
end = ']' level:'='* ']' &{ return levels[levels.length-1] === level.length; }
```

**Comment by hildjj** [comment] 2022-06-10 18:14
I'm going to close this since I think it's not-a-bug.  Please re-open if you feel like we didn't answer your question.

**Closed by hildjj** 2022-06-10 18:14 UTC
